version: "3.9"

services:
  db:
    image: postgres:14.5
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  pg_data:
